### ISSUE TITLE
Sorting of alphabetic strings is case-sensitive

### ISSUE THREAD

**Issue by conficient** [stevegreatrex/ko.plus#10]
Not sure if this is intended behaviour or not, but sorting of alphabetic strings is case-sensitive. I would normally expect a sort to default to case-insensitive.

http://jsfiddle.net/Quango/zhe7nexg/12/

**Comment by stevegreatrex** [comment]
Fixed in version 0.0.23

**Comment by conficient** [comment]
Thanks Steve
