### ISSUE TITLE
Method on ko.command to reset it

### ISSUE THREAD

**Issue by HakanL** [stevegreatrex/ko.plus#13]
I'm using the ko.command and I need to call it multiple times. But I want to be able to reset the failed flag and failMessage so a text bound to the failure message is cleared before I attempt the command again. Think a clear button in the UI, then the user can enter new data in an input box and attempt the command again.

**Comment by stevegreatrex** [comment]
This functionality has been included in the latest version (though not properly merged through GH, apparently)

**Comment by HakanL** [comment]
Thanks!
