### ISSUE TITLE
Assumes jQuery promises, not compatible with other promises like WinJS promises

### ISSUE THREAD

**Issue by tommck** [stevegreatrex/ko.plus#5]
jQuery promises are non-standard (i.e. don't follow the Promises/A spec) and so this will only work with jQuery promises because it expects "fail", "always", etc.

standard promises don't have these methods.

http://wiki.commonjs.org/wiki/Promises/A

**Comment by oliverkane** [comment]
@tommck , would look forward to it. I use Q for all my A+ promise needs so that would be a welcome change.
