### ISSUE TITLE
TypeScript definition file

### ISSUE THREAD

**Issue by conficient** [stevegreatrex/ko.plus#7]
I've had a shot at creating a definition file for TypeScript, please could you have a look and tell me if I've got anything terribly wrong?

https://github.com/borisyankov/DefinitelyTyped/pull/3644 

Not sure if you're familiar with TypeScript or not.

**Comment by stevegreatrex** [comment]
Hi Howard, thanks for this - the definitions all look good to me (though I must confess to having only a passing knowledge of TypeScript).

Let me know if you sort out the npm issue!
